!includeurl https://raw.githubusercontent.com/GrupaPracuj/C4-PlantUML/master/C4_Enterprise.puml
' uncomment the following line and comment the first to use locally
' !include C4_Enterprise.puml

' Scope: A single software system.
' Primary elements: The software system in scope.
' Supporting elements: People and software systems directly connected to the software system in scope.
' Intended audience: Everybody, both technical and non-technical people, inside and outside of the software development team.
